<a href="https://colab.research.google.com/github/ElrheaDeSouza/PythonWorkshop/blob/main/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=20
print(str(x)+" dollars")

20 dollars


In [ ]:
#check if the number entered is positive negative or 0
a=3
a=int(input("Enter a number"))
if a==0:
  print("Number is zero")
elif a>0:
  print("Number is positive")
else:
  print("Number is Negative")


Enter a number-8
Number is Negative


In [ ]:
#check if the number entered is positive negative or 0
a=int(input("Enter frst number"))
b=int(input("Enter second number"))
if a > b:
  print("a is greater "+str(a))
elif b>a:
  print("b is greater "+str(b))
else:
  print("Numbers are equal")


Enter frst number1
Enter second number4
b is greater4


In [ ]:
i=1
while i <= 5:
  if i==5:
    print("value reached five")
    break
  print(i)
  i=i+1

1
2
3
4
value reached five


In [ ]:
def Area(a,b):
  if a%2==0 and b%2==0:
    print("Numbers is even")
  elif a%2==0:
    print("a is even")
  elif b%2==0:
    print("a is even")
  else:
    print("Numbers is odd")

a=int(input("ENter first number"))
b=int(input("ENter second number"))
Area(a,b)



ENter first number2
ENter second number3
a is even


In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#To print odd numbers
for i in range(1,10,2):
  print(i)

1
3
5
7
9


In [ ]:
#lists
mylist=[19,20,'hello','hii','Apple']
mylist.append("Apple") #TO add at the end of list
mylist.insert(1,"orange") #To add items at specific location
mylist.pop()
mylist.remove("hii")
print(mylist)

[19, 'orange', 20, 'hello', 'Apple']


In [ ]:
for i in mylist:
  print(i)

19
20
hello
hii


In [ ]:
list1=[5,-2,10,8,51]
list2=[10,13,56,23,12,45]
list3=[]
list1.sort()
print(list1)
list3=list1 + list2
#list3=list1.extend(list2)
print(list3)
print(list3[-2])#TO print secondlast element
list3.reverse()
print(list3)
print (list3[:3])


[-2, 5, 8, 10, 51]
[-2, 5, 8, 10, 51, 10, 13, 56, 23, 12, 45]
12
[45, 12, 23, 56, 13, 10, 51, 10, 8, 5, -2]
[45, 12, 23]


In [ ]:
tuple1=("ap","ba")
tuple2=(90,"ch",10)
tuple3=tuple1+tuple2
print(tuple3)
#To update a tuple con=vert it to list and update it


('ap', 'ba', 90, 'ch', 10)


In [ ]:
myset={1,2,3}
myset.add("apple")
print(myset)
myset.remove(1)
print(myset)

{'apple', 1, 2, 3}
{'apple', 2, 3}


In [ ]:
set1={1,45,6}
set2={1,4,5,6}
set1.union(set2)
set1.intersection(set2)
set1.difference(set2)


{45}

In [ ]:
mydict = {"brand": "maruti", "model": "Baleno", "year": "1990", "price": "7 lakhs"}

# Print keys and values
print(mydict.keys())
print(mydict.values())

# Iterating through the dictionary and printing values
for i in mydict:
    print(mydict[i])

# Updating the "year" value
mydict["year"] = 2000
print(mydict)

# Correct update for the model
mydict.update({"model": "Audi"})
print(mydict)

mydict.popitem()
print(mydict)


dict_keys(['brand', 'model', 'year', 'price'])
dict_values(['maruti', 'Baleno', '1990', '7 lakhs'])
maruti
Baleno
1990
7 lakhs
{'brand': 'maruti', 'model': 'Baleno', 'year': 2000, 'price': '7 lakhs'}
{'brand': 'maruti', 'model': 'Audi', 'year': 2000, 'price': '7 lakhs'}
{'brand': 'maruti', 'model': 'Audi', 'year': 2000}


In [ ]:
wcWinners = {
    1975: "West Indies",
    1979: "West Indies",
    1983: "India",
    1987: "Australia",
    1991: "Pakistan",
    1996: "Sri Lanka",
    1999: "Australia",
    2003: "Australia",
    2011: "India"
}

wcWinner2000 = {}

for key, value in wcWinners.items():
    if key <= 2000:
        wcWinner2000[key] = value
print(wcWinner2000)


{1975: 'West Indies', 1979: 'West Indies', 1983: 'India', 1987: 'Australia', 1991: 'Pakistan', 1996: 'Sri Lanka', 1999: 'Australia'}


In [ ]:
tree={"A":['B','C'],"B":['D'],"C":['F'],"D":[],"F":['b']}
print(tree)

{'A': ['B', 'C'], 'B': ['D'], 'C': ['F'], 'D': [5], 'F': ['b']}


In [ ]:
import math
math.pi
help(math) #to work with various math functions

math.log(10)
math.ceil(4.679)
math.floor(3.18)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

3

In [ ]:
import statistics as st

In [ ]:
st.median([1,4,5,6,7])

5

In [ ]:
st.stdev([2,5,6,9])

2.886751345948129

In [ ]:
st.variance([2,5,6,9])

8.333333333333334

In [ ]:
st.mean([2,5,6,9])


5.5

In [ ]:
import random as rd

In [ ]:
nums=[12,13,23,56,80,]
rd.shuffle(nums)
print(nums)

[12, 80, 13, 56, 23]


In [ ]:
rd.randrange(1,100,2)

9

In [ ]:
rd.choice("Data Analytics")

'a'

In [ ]:
rd.randint(1,10)

8

In [ ]:
import numpy as np

In [ ]:
list1=[12,13,45,34]
arr=np.array(list1)

In [ ]:
n_array.shape

(3, 4)

In [ ]:
n_array.size

12

In [ ]:
new_array=n_array.reshape(4,3)
print(new_array)

[[0 3 4]
 [4 3 5]
 [1 2 4]
 [7 6 5]]


In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
mat.sum()

325

In [ ]:
mat1=np.array([[1,2,3],[1,1,1],[2,3,4]])
mat2=np.array([[1,3,3],[1,4,2],[2,3,1]])
print(mat1)
print(mat2)
sum=mat1+mat2
print("Sum")
print(sum)

dif=mat1-mat2
print("Diff")
print(dif)

mul=mat1*mat2
print("Mul")
print(mul)

[[1 2 3]
 [1 1 1]
 [2 3 4]]
[[1 3 3]
 [1 4 2]
 [2 3 1]]
Sum
[[2 5 6]
 [2 5 3]
 [4 6 5]]
Diff
[[ 0 -1  0]
 [ 0 -3 -1]
 [ 0  0  3]]
Mul
[[1 6 9]
 [1 4 2]
 [4 9 4]]


In [ ]:
n_array=np.array([[0,3,4,4],
                  [3,5,1,2],
                  [4,7,6,5]])
print(n_array)

[[0 3 4 4]
 [3 5 1 2]
 [4 7 6 5]]


In [ ]:
import pandas as pd
data={'Name':['michelle','john','jack','andrew'],'age':[20,67,56,34],'salary':[15000,50000,30000,9000]}
emp_df=pd.DataFrame(data)
print(emp_df)

       Name  age  salary
0  michelle   20   15000
1      john   67   50000
2      jack   56   30000
3    andrew   34    9000


In [ ]:
emp_df["department"]=['Hr','Operation','Finance','It']
print(emp_df)

       Name  age  salary department
0  michelle   20   15000         Hr
1      john   67   50000  Operation
2      jack   56   30000    Finance
3    andrew   34    9000         It


In [ ]:
Emp_id=[111,112,113,114]
emp_df.insert(loc=0,column='Emp_id', value=Emp_id)


ValueError: cannot insert Emp_id, already exists

In [ ]:
print(emp_df)

   Emp_id      Name  age  salary department
0     111  michelle   20   15000         Hr
1     112      john   67   50000  Operation
2     113      jack   56   30000    Finance
3     114    andrew   34    9000         It


In [ ]:
emp_df[['Name','salary']].min()

Name      andrew
salary      9000
dtype: object

In [ ]:
emp_df['department'].value_counts()

department
Hr           1
Operation    1
Finance      1
It           1
Name: count, dtype: int64

In [ ]:
emp_df[emp_df['salary']>40000]

Emp_id  Name  age  salary department
1     112  john   67   50000  Operation

In [ ]:
emp_df.drop("Emp_id", axis=1, inplace=True)

# Print the modified DataFrame
print(emp_df)

KeyError: "['Emp_id'] not found in axis"

In [ ]:
import pandas as pd


In [ ]:
from google.colab import files
uploaded =files.upload()

Saving Amazons Books Seeling data.xlsx to Amazons Books Seeling data.xlsx


In [ ]:
data=pd.read_excel("Amazons Books Seeling data.xlsx")
data

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
from google.colab import files
uploaded =files.upload()

Saving IRIS Test data.txt to IRIS Test data.txt


In [ ]:
data=pd.read_txt("IRIS Test data.txt")
data

AttributeError: module 'pandas' has no attribute 'read_txt'

In [ ]:
from google.colab import files
uploaded =files.upload()

In [ ]:
data=pd.read_json("iris.json")
data

sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [1]:
from google.colab import files
uploaded =files.upload()


Saving Mall_Customers.csv to Mall_Customers.csv


In [3]:
data=pd.read_csv("Mall_Customers.csv")
data

NameError: name 'pd' is not defined